[project]
name = "Rencher"
version = "1.1.2"
description = "A Ren'Py game manager, made with DDLC mods in mind"
requires-python = ">=3.12"
dependencies = [
    "pycairo==1.27.0; sys.platform == 'linux'",
    "pygobject==3.50.0; sys.platform == 'linux'",
    "cx-freeze>=8.3.0; sys.platform == 'linux'", # apparently doesn't build on windows?
    "rarfile>=4.2",
    "requests>=2.32.4",
    "thefuzz>=0.22.1",
    "watchdog>=6.0.0",
    "pygobject-stubs>=2.13.0",
    "tendo>=0.3.0",
]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["rencher"]

[tool.setuptools.packages.find]
where = ["."]
namespaces = false  # so only modules get added


[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "I",
]
extend-select = [
    "B",
    "COM",
]


[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false
