[project]
name = "Rencher"
version = "1.0.1"
description = "A Ren'Py game manager, made with DDLC mods in mind"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.6.9",
    "pycairo==1.27.0",
    "pygobject==3.50.0",
    "pygobject-stubs==2.12.0",
    "rarfile>=4.2",
    "requests>=2.32.4",
    "thefuzz>=0.22.1",
    "watchdog>=6.0.0",
]
