[project]
name = "rencher"
version = "0.1.0"
description = "A game manager for Ren'Py"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.6.9",
    "patool>=3.1.3",
    "pycairo==1.27.0",
    "pygobject==3.50.0",
    "pygobject-stubs==2.12.0",
    "thefuzz>=0.22.1",
    "watchdog>=6.0.0",
]
