[project]
name = "rencher"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "patool>=3.1.3",
    "pycairo==1.27.0",
    "pygobject==3.50.0",
    "pygobject-stubs==2.12.0",
    "pyinstaller>=6.11.1",
    "watchdog>=6.0.0",
]
