[project]
name = "Rencher"
version = "1.3.0"
description = "Play and mod Ren'Py games"
authors = [{name = "danatationn"}]
license = "GPL-3.0-or-later"
requires-python = ">=3.12"
dependencies = [
    "pycairo==1.27.0; sys.platform == 'linux'",
    "pygments>=2.20.0",
    "pygobject==3.50.0; sys.platform == 'linux'",
    "pypresence>=4.6.1",
    "rarfile>=4.2",
    "requests>=2.32.4",
    "rich>=14.3.3",
]

[tool.rencher]
copyright = "© 2026 danatationn"

[project.urls]
homepage = "https://github.com/danatationn/rencher"
issues = "https://github.com/danatationn/rencher/issues"

[dependency-groups]
dev = [
    "pygobject-stubs>=2.13.0",
    "cx-freeze>=8.6.2; sys.platform == 'win32'",
    "flatpak-pip-generator>=26.3.11; sys.platform == 'linux'",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["rencher"]

[tool.setuptools.packages.find]
where = ["."]
# so only modules get added
namespaces = false

[tool.pyright]
reportExplicitAny = false
reportMissingModuleSource = false
reportMissingParameterType = false
reportMissingTypeStubs = false
reportUnusedCallResult = false
reportImportCycles = false

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "I",
]
extend-select = [
    "B",
    "COM",
]
ignore = ["UP037"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false
