name: Rencher
on: 
  workflow_dispatch: 

jobs:
  windows-job:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git 
            mingw-w64-ucrt-x86_64-python 
            mingw-w64-ucrt-x86_64-python-pip 
            mingw-w64-ucrt-x86_64-python-gobject 
            mingw-w64-ucrt-x86_64-blueprint-compiler 
            mingw-w64-ucrt-x86_64-gtk4 
            mingw-w64-ucrt-x86_64-libadwaita 
            mingw-w64-ucrt-x86_64-gcc 
            mingw-w64-ucrt-x86_64-python-nuitka 
            mingw-w64-ucrt-x86_64-ntldd
      - name: Compile with Nuitka
        run: |
          pip install -r requirements.txt
          python build.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rencher-Windows
          path: 'Rencher.exe'