name: Rencher
on: 
  workflow_dispatch: 

jobs:
  windows-job:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-python 
            mingw-w64-ucrt-x86_64-python-pip 
      - name: Install dependencies
        run: python build-aux/install_deps.py
      - name: Freeze Rencher
        run: python build-aux/freeze.py
#      - name: Create NSIS Installer
#        run: 
#      - name: Upload Windows artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Rencher-Windows
#          path: 'Rencher.exe'