name: Rencher
on: 
  workflow_dispatch: 

jobs:
  linux-job:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: rencher-builder:latest
          load: true

      - name: Create container and extract files
        run: |
          docker create --name temp-container rencher-builder:latest
          docker cp temp-container:/app/build ./output/
          docker rm temp-container

      - id: freeze-dir
        run: |
          FREEZE_DIR=$(python3 -c "import sysconfig; print(f'exe.{sysconfig.get_platform()}-{sysconfig.get_python_version()}')")
          echo "FREEZE_DIR=$FREEZE_DIR" >> $GITHUB_OUTPUT

      - name: Upload frozen files
        uses: actions/upload-artifact@v4
        with:
          name: Rencher-Frozen-Linux
          path: ./output/$({ steps.freeze-dir.outputs.FREEZE_DIR })/

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Rencher-AppImage
          path: ./output/Rencher-x86_64.AppImage

  windows-job:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-python 
            mingw-w64-ucrt-x86_64-python-pip 
      - name: Install dependencies
        run: python build-aux/install_deps.py
      - name: Freeze Rencher
        run: python build-aux/freeze.py
#      - name: Create NSIS Installer
#        run: 
#      - name: Upload Windows artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Rencher-Windows
#          path: 'Rencher.exe'
#     wget this https://sourceforge.net/projects/nsis/files/NSIS%203/3.11/nsis-3.11.zip/download
#     and then do shit with it
#     or just try to use winget???