name: Rencher
on: [push, workflow_dispatch]

jobs:
  linux-job:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.10
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update && apt install -y \
            python3-dev \
            python3-pip \
            python3-venv \
            cmake \
            gobject-introspection \
            libgirepository1.0-dev \
            libgirepository-2.0-dev \
            libgtk-4-dev \
            patchelf \
            libadwaita-1-dev \
            ccache \
            blueprint-compiler \
            file \
            flatpak-builder \
            meson \
            nodejs
          pip install uv --break-system-packages
      - name: Setup environment
        run: |
          uv sync
          meson setup build -Dprefix=$(pwd)/build/root
          ninja -C build install
      - name: Cache Flatpak runtimes
        uses: actions/cache@v4
        with:
          path: /var/lib/flatpak
          key: flatpak-${{ runner.os }}-49
      - name: Package Flatpak
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --system
          flatpak install org.gnome.Sdk//49 org.gnome.Platform//49 --system -y --no-related
          flatpak-builder --install --user build/flatpak com.github.danatationn.rencher.yml
          flatpak build-bundle ~/.local/share/flatpak/repo build/Rencher.flatpak com.github.danatationn.rencher
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rencher-Linux-Flatpak
          path: build/Rencher.flatpak
      - name: Make AppImage
        if: false
        run: |
          wget https://github.com/niess/python-appimage/releases/download/python3.14/python3.14.0-cp314-cp314t-manylinux2014_x86_64.AppImage
          chmod +x python3.14.0-cp314-cp314t-manylinux2014_x86_64.AppImage
          ./python3.14.0-cp314-cp314t-manylinux2014_x86_64.AppImage --appimage-extract
          wget -c "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"
          wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-gtk.sh

  windows-job:
    name: Windows
    runs-on: windows-2025
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-python-pip
            mingw-w64-ucrt-x86_64-nsis
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-libadwaita
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-blueprint-compiler
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-uv
            mingw-w64-ucrt-x86_64-gobject-introspection
            mingw-w64-ucrt-x86_64-ntldd
            mingw-w64-ucrt-x86_64-python-cx-freeze

      - name: Setup Environment
        run: |
          uv sync
          source .venv/Scripts/activate
          meson setup build -Dprefix=$(pwd)/build/root/
          ninja -C build install

      - name: Freeze Rencher
        id: freeze
        run: |
          source .venv/Scripts/activate
          python freeze.py build/root/
          FREEZE_DIR=$(python -c "import sysconfig; print(f'exe.{sysconfig.get_platform()}-{sysconfig.get_python_version()}')")
          echo "FREEZE_DIR=$FREEZE_DIR" >> $GITHUB_OUTPUT

      - name: Build NSIS installer
        run: ninja -C build makensis

      - name: Upload frozen files artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rencher-Windows-Portable
          path: build/${{ steps.freeze.outputs.FREEZE_DIR }}

      - name: Upload NSIS installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rencher-Windows-Installer
          path: build/RencherInstaller.exe
